Les demandes de données transitent par le DataPass api.gouv.fr
entrepreneur-interet-general/CartoBio-Presentation pull request #68
Opened 2020-10-01 13:39 UTC by oncletom

2020-10-01 14:23 UTC, oncletom commented
![](https://github.trello.services/images/mini-trello-icon.png) [Finaliser le branchement de api.gouv.fr sur cartobio.org](https://trello.com/c/uvUYAcyd/432-finaliser-le-branchement-de-apigouvfr-sur-cartobioorg)

2020-10-05 11:57 UTC, lucas-bch approved these changes

2020-10-05 11:58 UTC, lucas-bch commented on src/views/Home.vue
> +              <v-btn :href="signupUrl" @click.stop round outline>
```suggestion
              <v-btn :href="signupUrl" target="_blank" @click.stop round outline>
```

2020-10-05 11:59 UTC, lucas-bch commented on src/views/Landing/Territory.vue
> +        <v-btn :href="signupUrl" large outline round color="primary" class="mb-5 mt-4">
```suggestion
        <v-btn :href="signupUrl" target="_blank" large outline round color="primary" class="mb-5 mt-4">
```

2020-10-05 11:59 UTC, lucas-bch requested changes

2020-10-05 11:59 UTC, lucas-bch commented on src/views/Landing/Territory.vue
> +        <v-btn :href="signupUrl" large outline round color="primary" class="mb-5 mt-4">
```suggestion
        <v-btn :href="signupUrl" target="_blank" large outline round color="primary" class="mb-5 mt-4">
```

2020-10-05 12:13 UTC, merged